### ISSUE TITLE
[BUG] - URLSearchParams unsupported on IOS

### ISSUE THREAD

**Issue by MinisculeGirraffe** [vultr/vultr-node#372]
**Describe the bug**

Unable to preform any POST requests on IOS devices due to URLSearchParams being unsupported. GET requests are still able to be preformed due to the API key being embedded in the headers.

**To Reproduce**
Utilize any POST requests in the library

**Expected behavior**
Parameters should be URL encoded when sent from an IOS device

**Screenshots**
![Screen Shot 1399-06-09 at 14 16 19](https://user-images.githubusercontent.com/50641020/91667633-ae321580-eacb-11ea-9f9c-217929a50d00.png)

See screenshot sent from an IOS device using the below code

![Screen Shot 1399-06-09 at 14 19 26](https://user-images.githubusercontent.com/50641020/91667653-d15cc500-eacb-11ea-85ae-871c470208a7.png)

**Desktop (please complete the following information where applicable:**
 - OS: iOS
 - Language Version NodeJS 12
 - Browser Stock browser
 - Version Any

**Additional context**
The fix for this is to use a generic polyfill to encode the URL params.

**Comment by MinisculeGirraffe** [comment]
I submitted [PR 373](https://github.com/vultr/vultr-node/pull/373) to fix this issue. Confirmed on my IOS devices that this resolves the error

**Comment by ddymko** [comment]
@MinisculeGirraffe Thanks for fixing this! We created a new milestone for v0.5.0 with your change and a few others which will go out by the end of the week.
