### ISSUE TITLE
[Feature] - Add Support for Vultr API v2

### ISSUE THREAD

**Issue by spencerkordecki** [vultr/vultr-node#388]
Add support for V2 of the [Vultr API](https://www.vultr.com/api/v2/)

**Comment by spencerkordecki** [comment]
V2 work is completed on the [V2 branch](https://github.com/vultr/vultr-node/tree/v2).

**Comment by ddymko** [comment]
Updated branches

master -> is now the v2 codebase
v1 -> old master (v1) codebase
