### ISSUE TITLE
[Feature] Typescript Support

### ISSUE THREAD

**Issue by Danzondo** [vultr/vultr-node#393]
It would be much easier to work with the Library, if typescript-definitions would be available for it.

**Comment by eonil** [comment]
+1 for this. Type annotation & check is the key for productivity. Please consider.

**Comment by 634396b** [comment]
Please :D!

**Comment by theDanielJLewis** [comment]
Nearly 3 years later and I would still love to see this, too.

**Comment by AFatalErrror** [comment]
Will be implemented in a new repo
