### ISSUE TITLE
1.0.2 seems to have broken something

### ISSUE THREAD

**Issue by theDanielJLewis** [vultr/vultr-node#416]
I have not changed my Vultr code at all, and vultr-node 1.0.2 seems to have broken things for me. It's not connecting with the Vultr API anymore for creation or deletion.

I receive no error messages, simply a silent hang.

Before 1.0.2, I was manually forcing number fields to Number type. But that shouldn't make a difference for 1.0.2, right?

**Comment by spencerkordecki** [comment]
1.0.2 includes #397 which allows for passing in both String and Number for endpoints that require a parameter. I'm investigating now and seeing what the issue is here on 1.0.2, and specifically with Number typed variables being sent in.

**Comment by spencerkordecki** [comment]
@theDanielJLewis fixed in release 1.0.3!

**Comment by theDanielJLewis** [comment]
I'm sorry it took me a while to confirm, but this does, indeed, seem to be fixed. Thank you!
