### ISSUE TITLE
Why are request objects in js files and not json?

### ISSUE THREAD

**Issue by j4qfrost** [vultr/vultr-node#430]
If the objects are json objects they would be more easily migrated to different languages. Is there a particular reason why this is the case?

**Comment by spencerkordecki** [comment]
@j4qfrost I don't quite follow the question here, could you please clarify? If you're talking about the files in the `src/` directory, those are .js files so we can just import them and access the properties instead of having to parse the JSON first.

**Comment by j4qfrost** [comment]
So the objects are already being pulled into the index.js file with require, which also parses the json objects for you when you import them. The intention behind switching from js to json is that other languages can readily parse them since json parsers are more commonplace and ready to use than say js to golang parsers. The only reasons I can see for keeping your objects in js files is that you want to keep multiple objects in those files or you plan on placing functions in the objects.
