### ISSUE TITLE
[Feature] - V2 API does not include some information

### ISSUE THREAD

**Issue by duclvz** [vultr/vultr-node#443]
The new v2 API listInstances() result does not include some properties like `pending_charges`, `cost_per_month`, `current_bandwidth_gb` which are very important to managing cloud instances.

Does anyone can help me get that data by using v2 API?

**Comment by ddymko** [comment]
These fields were removed from the listInstance for v2.

Bandwidth is now it's own call:
https://www.vultr.com/api/#operation/get-instance-bandwidth

The call for this would be `getInstanceBandwidth`
https://vultr.github.io/vultr-node/instances.html 

Pending charges is in account and cost of the plan is in the plans list
https://www.vultr.com/api/#operation/get-account
https://www.vultr.com/api/#operation/list-plans
