### ISSUE TITLE
[BUG] - Release pipeline fails on npm publish

### ISSUE THREAD

**Issue by gabos31** [vultr/vultr-node#447]
Please post latest version to npm registry

**Comment by ddymko** [comment]
There is a silent failure in our deploy process during the NPM publishing. We will look into resolving that

**Comment by ddymko** [comment]
@gabos31 I published the package by hand. Thanks for pointing this out looks like our release pipeline has a silent failure which prevented publishing to NPM.

v2.0.3 should be up now
https://www.npmjs.com/package/@vultr/vultr-node
