### ISSUE TITLE
[BUG] - firewall.createRules() does not work

### ISSUE THREAD

**Issue by gabos31** [vultr/vultr-node#449]
**Describe the bug**
When trying to execute a function, an empty object is immediately returned, but the rule is not created. With curl (with the same parameters) everything works correctly.

**Comment by spencerkordecki** [comment]
@gabos31 if the rule is already created, then the call will throw an error. I was able to successfully create firewall rule via the library when using a port where a rule didn't already exist.

That said, I can definitely see where our error handling can be improved and have opened #450 to deal with this.

**Comment by gabos31** [comment]
@spencerkordecki yes, the error was on my side, I was passing the subnet_size as a number (since it is returned as a number when asking for a list of rules), not as a string. It would be great to receive informative error messages in such cases.
