### ISSUE TITLE
[BUG] - instances.updateInstance() does not work correctly

### ISSUE THREAD

**Issue by gabos31** [vultr/vultr-node#451]
**Describe the bug**

1. Error in the code https://github.com/vultr/vultr-node/blob/a7aa8c698b325d40ec63223732836b1c11d7445b/src/util.js#L47
should be: `(newObj, key) => Object.assign(newObj, { [key]: userParameters[key] }),`
2. Parameters that are passed empty (''), for example, the security group from which you want to exclude the instance, are not included in the request body. This is due to a parameter validation error.
For example, this can be avoided by adding an additional condition to https://github.com/vultr/vultr-node/blob/a7aa8c698b325d40ec63223732836b1c11d7445b/src/index.js#L61
should be: `} else if (userParameter || userParameter === '') {`

**Comment by ddymko** [comment]
@gabos31 Thanks for reporting the issues! Feel free to submit PRs to fix them if you want.

**Comment by gabos31** [comment]
@ddymko I created a PR, but there are some problems with checks. https://github.com/vultr/vultr-node/pull/452

**Comment by ddymko** [comment]
merged in #452
