### ISSUE TITLE
[Feature] - Firewall Rule field change

### ISSUE THREAD

**Issue by ddymko** [vultr/vultr-node#624]
Firewall Rules

In [list](https://www.vultr.com/api/#operation/list-firewall-group-rules) and [get](https://www.vultr.com/api/#operation/get-firewall-group-rule) calls, the type field is deprecated. Use ip_type instead.

**Comment by afady** [comment]
No changes necessary here as far as I can tell:
https://github.com/vultr/vultr-node/blob/master/src/api/firewall.js#L109
https://github.com/vultr/vultr-node/blob/master/test/api/firewall.test.js#L81
